import { supabase } from '@/integrations/supabase/client';
import { CodeImprovementService } from './CodeImprovementService';
import { CodeIssue } from './CodeAnalysisService';

export interface SandboxRepo {
  id: number;
  name: string;
  full_name: string;
  html_url: string;
  description: string;
  created_at: string;
  original_pr_url?: string;
  original_score?: number;
}

export interface PRImprovement {
  originalPR: {
    url: string;
    score: number;
    title: string;
  };
  improvedPR: {
    url: string;
    repoUrl: string;
  };
  improvements: string;
  sandboxRepo: SandboxRepo;
}

export class SandboxService {
  private static instance: SandboxService;
  private improvementService: CodeImprovementService;

  private constructor() {
    this.improvementService = CodeImprovementService.getInstance();
  }

  public static getInstance(): SandboxService {
    if (!SandboxService.instance) {
      SandboxService.instance = new SandboxService();
    }
    return SandboxService.instance;
  }

  /**
   * Get GitHub access token from current session
   */
  private async getGitHubToken(): Promise<string> {
    const { data: { session } } = await supabase.auth.getSession();
    const token = session?.provider_token;
    
    if (!token) {
      throw new Error('No GitHub access token found. Please re-authenticate.');
    }
    
    return token;
  }

  /**
   * Improve an existing PR in a sandbox repository
   */
  public async improvePRInSandbox(
    prUrl: string,
    prTitle: string,
    originalScore: number,
    files: Array<{ filename: string; patch: string; content: string }>,
    issues: CodeIssue[]
  ): Promise<PRImprovement> {
    const token = await this.getGitHubToken();
    const timestamp = Date.now();
    const repoName = `pullwise-improved-${timestamp}`;

    // Create sandbox repository
    const repo = await this.createRepo(repoName, prUrl, token);
    
    // Wait for GitHub to initialize
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Get default branch
    const defaultBranch = await this.getDefaultBranch(repo.full_name, token);
    
    // Create branch for original code
    await this.createBranch(repo.full_name, 'original-pr', defaultBranch.sha, token);
    
    // Add original files to original-pr branch
    for (const file of files) {
      await this.createFileInBranch(
        repo.full_name,
        'original-pr',
        {
          path: file.filename,
          content: file.content,
          message: `feat: Add original file ${file.filename}`,
        },
        token
      );
    }
    
    // Create branch for improved code
    const originalBranchInfo = await this.getBranchSha(repo.full_name, 'original-pr', token);
    await this.createBranch(repo.full_name, 'improved-pr', originalBranchInfo.sha, token);
    
    // Apply improvements to files
    const improvements: string[] = [];
    for (const file of files) {
      const improved = this.improvementService.applyFixes(file.content, issues.filter(i => i.file === file.filename));
      
      if (improved.changes.length > 0) {
        await this.updateFileInBranch(
          repo.full_name,
          'improved-pr',
          {
            path: file.filename,
            content: improved.improvedCode,
            message: `fix: Apply improvements to ${file.filename}`,
          },
          token
        );
        
        improvements.push(this.improvementService.generateImprovementSummary(improved.changes));
      }
    }
    
    // Create PR for improved version
    const improvedPR = await this.createPR(
      repo.full_name,
      {
        title: `✨ Improved: ${prTitle}`,
        body: `# PR Improvements\n\n` +
              `**Original PR**: ${prUrl}\n` +
              `**Original Score**: ${originalScore}%\n\n` +
              `## Changes Applied\n\n${improvements.join('\n\n---\n\n')}` +
              `\n\n---\n\n*This improved version was automatically generated by PullWise to demonstrate best practices.*`,
        head: 'improved-pr',
        base: defaultBranch.name,
      },
      token
    );
    
    return {
      originalPR: {
        url: prUrl,
        score: originalScore,
        title: prTitle,
      },
      improvedPR: {
        url: improvedPR.html_url,
        repoUrl: repo.html_url,
      },
      improvements: improvements.join('\n\n'),
      sandboxRepo: {
        ...repo,
        original_pr_url: prUrl,
        original_score: originalScore,
      },
    };
  }

  /**
   * Create a new repository
   */
  private async createRepo(name: string, originalPRUrl: string, token: string): Promise<SandboxRepo> {
    const response = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name,
        description: `🔧 Improved version of ${originalPRUrl} - Created by PullWise`,
        private: false,
        auto_init: true,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to create repository: ${error.message}`);
    }

    return await response.json();
  }

  /**
   * Get branch SHA
   */
  private async getBranchSha(repoFullName: string, branchName: string, token: string): Promise<{ sha: string }> {
    const response = await fetch(`https://api.github.com/repos/${repoFullName}/branches/${branchName}`, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
      },
    });

    const branch = await response.json();
    return { sha: branch.commit.sha };
  }

  /**
   * Update a file in a specific branch
   */
  private async updateFileInBranch(
    repoFullName: string,
    branch: string,
    file: { path: string; content: string; message: string },
    token: string
  ): Promise<void> {
    // Get current file SHA
    const fileResponse = await fetch(`https://api.github.com/repos/${repoFullName}/contents/${file.path}?ref=${branch}`, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
      },
    });

    const fileData = await fileResponse.json();

    await fetch(`https://api.github.com/repos/${repoFullName}/contents/${file.path}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: file.message,
        content: btoa(unescape(encodeURIComponent(file.content))),
        branch: branch,
        sha: fileData.sha,
      }),
    });
    
    await new Promise(resolve => setTimeout(resolve, 500));
  }

  /**
   * List sandbox repositories
   */
  public async listSandboxRepos(): Promise<SandboxRepo[]> {
    const token = await this.getGitHubToken();

    const response = await fetch('https://api.github.com/user/repos?per_page=100&sort=created', {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
      },
    });

    const repos = await response.json();
    
    return repos.filter((repo: SandboxRepo) => 
      repo.name.startsWith('pullwise-improved-')
    );
  }

  /**
   * Delete a sandbox repository
   */
  public async deleteSandboxRepo(repoFullName: string): Promise<void> {
    const token = await this.getGitHubToken();

    const response = await fetch(`https://api.github.com/repos/${repoFullName}`, {
      method: 'DELETE',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
      },
    });

    if (!response.ok && response.status !== 204) {
      throw new Error('Failed to delete repository');
    }
  }

  /**
   * Get default branch information
   */
  private async getDefaultBranch(repoFullName: string, token: string): Promise<{ name: string; sha: string }> {
    const response = await fetch(`https://api.github.com/repos/${repoFullName}`, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
      },
    });

    const repo = await response.json();
    const defaultBranch = repo.default_branch || 'main';

    const branchResponse = await fetch(`https://api.github.com/repos/${repoFullName}/branches/${defaultBranch}`, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
      },
    });

    const branch = await branchResponse.json();
    return { name: defaultBranch, sha: branch.commit.sha };
  }

  /**
   * Create a new branch
   */
  private async createBranch(repoFullName: string, branchName: string, sha: string, token: string): Promise<void> {
    await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: sha,
      }),
    });
    
    await new Promise(resolve => setTimeout(resolve, 500));
  }

  /**
   * Create a file in a specific branch
   */
  private async createFileInBranch(
    repoFullName: string,
    branch: string,
    file: { path: string; content: string; message: string },
    token: string
  ): Promise<void> {
    await fetch(`https://api.github.com/repos/${repoFullName}/contents/${file.path}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: file.message,
        content: btoa(unescape(encodeURIComponent(file.content))),
        branch: branch,
      }),
    });
    
    await new Promise(resolve => setTimeout(resolve, 500));
  }

  /**
   * Create a pull request
   */
  private async createPR(
    repoFullName: string,
    pr: { title: string; body: string; head: string; base: string },
    token: string
  ): Promise<{ html_url: string; number: number }> {
    const response = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(pr),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to create PR: ${error.message}`);
    }

    return await response.json();
  }
}
